import { createReducer } from 'redux-act';

import { setupNewMatch } from '../actions/chessBoardActions';
import Constants from '../util/constants';

const initialState = {
  positions: {
    A1: null,
    A2: null,
    A3: null,
    A4: null,
    A5: null,
    A6: null,
    A7: null,
    A8: null,
    B1: null,
    B2: null,
    B3: null,
    B4: null,
    B5: null,
    B6: null,
    B7: null,
    B8: null,
    C1: null,
    C2: null,
    C3: null,
    C4: null,
    C5: null,
    C6: null,
    C7: null,
    C8: null,
    D1: null,
    D2: null,
    D3: null,
    D4: null,
    D5: null,
    D6: null,
    D7: null,
    D8: null,
    E1: null,
    E2: null,
    E3: null,
    E4: null,
    E5: null,
    E6: null,
    E7: null,
    E8: null,
    F1: null,
    F2: null,
    F3: null,
    F4: null,
    F5: null,
    F6: null,
    F7: null,
    F8: null,
    G1: null,
    G2: null,
    G3: null,
    G4: null,
    G5: null,
    G6: null,
    G7: null,
    G8: null,
    H1: null,
    H2: null,
    H3: null,
    H4: null,
    H5: null,
    H6: null,
    H7: null,
    H8: null,
  },
};

const reducerMap = createReducer({
  [setupNewMatch]: state => Object.assign({}, state, {
    positions: {
      A8: Constants.Pieces.PlayerOne.Rook,
      B8: Constants.Pieces.PlayerOne.Knight,
      C8: Constants.Pieces.PlayerOne.Bishop,
      D8: Constants.Pieces.PlayerOne.Queen,
      E8: Constants.Pieces.PlayerOne.King,
      F8: Constants.Pieces.PlayerOne.Bishop,
      G8: Constants.Pieces.PlayerOne.Knight,
      H8: Constants.Pieces.PlayerOne.Rook,
      A7: Constants.Pieces.PlayerOne.Pawn,
      B7: Constants.Pieces.PlayerOne.Pawn,
      C7: Constants.Pieces.PlayerOne.Pawn,
      D7: Constants.Pieces.PlayerOne.Pawn,
      E7: Constants.Pieces.PlayerOne.Pawn,
      F7: Constants.Pieces.PlayerOne.Pawn,
      G7: Constants.Pieces.PlayerOne.Pawn,
      H7: Constants.Pieces.PlayerOne.Pawn,
      A2: Constants.Pieces.PlayerTwo.Pawn,
      B2: Constants.Pieces.PlayerTwo.Pawn,
      C2: Constants.Pieces.PlayerTwo.Pawn,
      D2: Constants.Pieces.PlayerTwo.Pawn,
      E2: Constants.Pieces.PlayerTwo.Pawn,
      F2: Constants.Pieces.PlayerTwo.Pawn,
      G2: Constants.Pieces.PlayerTwo.Pawn,
      H2: Constants.Pieces.PlayerTwo.Pawn,
      A1: Constants.Pieces.PlayerTwo.Rook,
      B1: Constants.Pieces.PlayerTwo.Knight,
      C1: Constants.Pieces.PlayerTwo.Bishop,
      D1: Constants.Pieces.PlayerTwo.Queen,
      E1: Constants.Pieces.PlayerTwo.King,
      F1: Constants.Pieces.PlayerTwo.Bishop,
      G1: Constants.Pieces.PlayerTwo.Knight,
      H1: Constants.Pieces.PlayerTwo.Rook,
    },
  }),
}, initialState);

export default reducerMap;
